# Generated by Django 3.0.7 on 2020-08-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.ImageField(upload_to='pics')),
                ('title', models.CharField(default='Blog on Programming', max_length=100)),
                ('fname', models.CharField(default='Anonymous', max_length=50)),
                ('lname', models.CharField(default='', max_length=60)),
                ('designation', models.CharField(default='Coder', max_length=150)),
                ('date', models.DateTimeField()),
                ('content', models.CharField(default='', max_length=7000)),
                ('slug', models.SlugField(max_length=300)),
            ],
        ),
    ]
