# Generated by Django 3.0.7 on 2020-08-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='Programming', max_length=500),
        ),
    ]
