# Generated by Django 3.0.7 on 2020-08-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Post', '0005_remove_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='fname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='lname',
        ),
    ]
