# Generated by Django 3.0.7 on 2020-08-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200820_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pic.jpg', upload_to='Profile Photos'),
        ),
    ]
