# Generated by Django 3.0.7 on 2020-08-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='Anonymus', max_length=50)),
                ('lname', models.CharField(default='Anonymus', max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(default='Technical Error', max_length=150)),
                ('date', models.DateTimeField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
